version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ../src/ui
    image: ${USER_NAME}/ui:${VERSION}
    ports:
      - ${UI_P}:${UI_P}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
        fluentd-async: 'true'
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    build: ../src/post-py
    image: ${USER_NAME}/post:${VERSION}
    networks:
      - front_net
      - back_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
        fluentd-async: 'true'
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  comment:
    build: ../src//comment
    image: ${USER_NAME}/comment:${VERSION}
    networks:
      - front_net
      - back_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net # Задаем время хранения метрик в 1 день

  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
  front_net:
