---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: reddit
    component: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: ui
  template:
    metadata:
      name: ui
      labels:
        app: reddit
        component: ui
    spec:
      containers:
        - image: voovik59/ui # Не забудьте подставить свой образ
          name: ui
          env:
            - name: ENV # Извлекаем значение из контекста запуска
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
