version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_V}
    volumes:
      - post_db:/data/db
    networks:
      - back_net

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_V}
    volumes:
      - ui_volume:/app
    ports:
      - ${APP_PORT}:9292/tcp
    networks:
      - front_net
    command: puma --debug -w 2

  post:
    build: ./post-py
    volumes:
      - post_volume:/app
    image: ${USERNAME}/post:${POST_V}
    networks:
      - front_net
      - back_net

  comment:
    build: ./comment
    volumes:
      - comment_volume:/app
    image: ${USERNAME}/comment:${COMMENT_V}
    networks:
      - front_net
      - back_net
    command: puma --debug -w 2

volumes:
  post_db:
  ui_volume:
  post_volume:
  comment_volume:

networks:
  back_net:
  front_net:
